import {chromium} from 'playwright-core';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
const root = path.resolve('dist');
const types = {'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.webp':'image/webp','.png':'image/png','.woff2':'font/woff2'};
const server = createServer(async (req, res) => { const p = new URL(req.url, 'http://x').pathname.replace(/^\//, '') || 'index.html';
  try { res.setHeader('Content-Type', types[path.extname(p)] || 'application/octet-stream'); res.end(await readFile(path.join(root, p))); } catch { res.writeHead(404); res.end(); } });
await new Promise(r => server.listen(0, '127.0.0.1', r));
const browser = await chromium.launch({channel:'msedge', headless:true});
const context = await browser.newContext({viewport:{width:390, height:844}, deviceScaleFactor:2, isMobile:true, hasTouch:true, serviceWorkers:'block'});
await context.addInitScript(() => { if (!sessionStorage.getItem('i')) { sessionStorage.setItem('i','1'); localStorage.setItem('vmk-group', '101'); localStorage.setItem('vmk-onboarded', '1'); } });
const page = await context.newPage(); page.on('pageerror', e => console.log('PAGE ERROR', e.message));
const cdp = await context.newCDPSession(page);
await page.goto(`http://127.0.0.1:${server.address().port}/`); await page.waitForSelector('.lesson'); await page.waitForTimeout(500);
await page.click('.header-actions [aria-label="Оформление"]'); await page.waitForTimeout(600);
const touch = (type, x, y) => cdp.send('Input.dispatchTouchEvent', {type, touchPoints:type === 'touchEnd' ? [] : [{x, y}]});
async function swipe(sel, dx) { const b = await page.locator(sel).boundingBox(); const y = b.y + b.height/2; let x = b.x + b.width/2; await touch('touchStart', x, y);
  for (let i = 0; i < 10; i++) { x += dx/10; await touch('touchMove', x, y); await page.waitForTimeout(16); } await touch('touchEnd', x, y); await page.waitForTimeout(900); }
const st = () => page.evaluate(() => `theme ${document.documentElement.dataset.theme} / style ${document.documentElement.dataset.style} / name «${document.querySelector('.dial-name')?.textContent}» / centered ${document.querySelector('.theme-dial [aria-selected=true]')?.getAttribute('aria-label')}`);
console.log('open      ', await st());
await swipe('.theme-dial', -120); console.log('themes ←  ', await st());
await swipe('.theme-dial', -200); console.log('themes ←← ', await st());
await swipe('.theme-dial', 140); console.log('themes →  ', await st());
await page.click('.scheme-switch [role=radio]:nth-child(2)'); await page.waitForTimeout(600); console.log('light     ', await st());
await swipe('.theme-dial', -120); console.log('light ←   ', await st());
await swipe('.style-dial', -110); console.log('style ←   ', await st());
await swipe('.style-dial', 110); console.log('style →   ', await st());
await page.locator('.theme-dial button').nth(3).click(); await page.waitForTimeout(900); console.log('tap 4th  ', await st());
await page.keyboard.press('Escape'); await page.waitForTimeout(300);
await page.reload(); await page.waitForSelector('.lesson'); console.log('reload    ', await page.evaluate(() => document.documentElement.dataset.theme + ' / ' + document.documentElement.dataset.style));
await browser.close(); server.close();
